### ISSUE TITLE
peer dependencies error after published 1.4.3 version

### ISSUE THREAD

**Issue by r4costa** [mzuccaroli/angular-google-tag-manager#105]
Hi,

In my project with Angular 8 (sorry about that), if you delete node-modules and run "npm install' I got 

`npm WARN angular-google-tag-manager@1.4.3 requires a peer of @angular/common@^12.0.3 but none is installed. You must install peer dependencies yourself.`

Ok, just a WARN.. In my packahe.json I have:

```
"dependencies": {
...
"angular-google-tag-manager": "^1.4.1",
...
}
```

After install, doesn't appears "google-tag-manager" folder inside node-modules and when I run my project or execute testes, I got:

`Cannot find module 'angular-google-tag-manager' from 'src/app/[project file].ts'`

I solved with

```
"dependencies": {
...
"angular-google-tag-manager": "=1.4.1",
...
}

```

But I don't know why I got that error. That didn't happen with 1.4.2 version published.

**Comment by mzuccaroli** [comment]
1.4.3 version is released to add angular 13 support, your angular version is quite old all dependancies are, the best solution is to use an older releaser of the library, i think that version 1.2 or older was officially tested with angular 8
the core lib hasn't changed so you can use older version with your project . If surprisingly v 1.4.2 work with your project you can safely use that otherwise try older versions:
`npm install angular-google-tag-manager@1.2`
