### ISSUE TITLE
404 on https://www.googletagmanager.com/gtm.js?id=...

### ISSUE THREAD

**Issue by sergey-karlo** [mzuccaroli/angular-google-tag-manager#2]
When I user GoogleTagManagerService I receive 404 on this URL https://www.googletagmanager.com/gtm.js?id=<MY_ID>

Correct URL should be https://www.googletagmanager.com/gtag/js?id=<MY_ID>

This one also 404
https://www.googletagmanager.com/ns.html?id=<MY_ID>

It's better to make it possible to configure it, same as googleTagManagerId.

**Comment by mzuccaroli** [comment]
according to the official documentation https://developers.google.com/tag-manager/quickstart
the include script is  
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXX');</script>
<!-- End Google Tag Manager -->
```

so the url "...gtm.js?id="  works fine in many projects  sincerly I don't konw the "...gtag/js?id=" urls and how they work

is it possible that you have some problems in providing your GTM id in your module?

**Comment by sergey-karlo** [comment]
I've checked it several times. ID is correct.
And as I mentioned, this one works https://www.googletagmanager.com/gtag/js?id=<MY_ID>
So ID is correct for sure.

The URL I'd provided is generated by GTM from site settings page. The complete code is:

 
<script async src="https://www.googletagmanager.com/gtag/js?id=<MY_ID>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<MY_ID>');
</script>

**Comment by mzuccaroli** [comment]
OK the problem here is that the code you have pasted is for google analytics  not for google tag manager

so I presume that your ID is an analytics id, something like _UA-112233456-1_
the GTM id is something like: _GTM-W3T4XYZ_

these are two different services but you can include analytics code via GTM integration, take a look to this article: https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2 
and the official google guide on how to integrate analytics on GTM: https://support.google.com/tagmanager/answer/6107124?hl=en

**Comment by sergey-karlo** [comment]
Yes, you are right! It's code from analytics. My fault.

Thanks for help
