### ISSUE TITLE
Error: Google tag manager ID not provided when API sends null instead of GTM_ID

### ISSUE THREAD

**Issue by marek-webb** [mzuccaroli/angular-google-tag-manager#97]
Hello.

I am providing GTM_ID dynamically like described here: https://github.com/mzuccaroli/angular-google-tag-manager/issues/58#issuecomment-808074457 but I have problem - sometimes my API cannot return the GTM_ID Tag and I have null as a value here. The error is:
```
core.js:6241 ERROR Error: Google tag manager ID not provided.
    at new GoogleTagManagerService (angular-google-tag-manager.js:27
```

How can I fix this?

Thank you
M.

**Comment by mzuccaroli** [comment]
Hi Marek,
the dynamic loading of gtm id is not actually supported by the library due to issues like yours.

The only solutions are workarounds to fetch the data before the  app and the gtm module are fully loaded and consequentially handle the fetch failure because data fetch is inherently unreliable.

In your case i think the a solution could be  provide a default ID in case of failure.

I close the issue because is not strictly related to the library funcionality.

**Comment by marek-webb** [comment]
Thank you.
